### PR TITLE
Use BOARD_SEPOLICY_DIRS instead of BOARD_SEPOLICY_UNION

### PR DESCRIPTION
**Pull request by TingyiChen**

### CODE REVIEW

**Comment by TingyiChen** [comment]
screenshotYou see

**Comment by dev-harsh1998** [comment]
Use MY tree for cm14.1

**Comment by TingyiChen** [comment]
@dev-harsh1998 i am now porting kernel for wt86528.i added missing header files now i am testing

**Comment by TingyiChen** [comment]
@dev-harsh1998 see telegram plz.i sent you a message and could you help me?

**Pull request closed without merging**
